# ucoa_reference.py — UCOA Reference Explorer
# NM PED School Budget Bureau
#
# Reads the UCOA source of truth from ./data/ucoa_<dim>.csv — five per-dimension files
# generated by build_ucoa.py from the OBMS COA Configuration Report + the PSAB description
# layer. The Google Sheet is no longer in the loop; the committed CSVs are the truth.
# Design language matches PED Contacts Manager (Merge_ped_contacts_v2.py).

import pandas as pd
import streamlit as st
from datetime import datetime
from pathlib import Path
import base64
from io import BytesIO

try:
    from PIL import Image
    HAS_PIL = True
except ImportError:
    HAS_PIL = False

# ─── Page config ──────────────────────────────────────────────────────
st.set_page_config(
    page_title="UCOA Reference Explorer",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Brand CSS ────────────────────────────────────────────────────────
# Palette mirrors Contacts Manager exactly:
#   Primary teal : #245d62   Dark teal : #1a474b
#   Gold          : #edc872  Coral     : #c64c43  (alerts only)
st.markdown("""
<style>
.block-container { padding-top: 3rem !important; max-width: 1180px; }

h1, h2, h3, h4 { color: #245d62; font-weight: 600; }

.ped-eyebrow {
    font-size: 11px; letter-spacing: .12em; text-transform: uppercase;
    color: #7a8a86; font-weight: 600;
}
.ped-title {
    font-family: Georgia, "Times New Roman", serif;
    font-size: 1.6rem; color: #245d62; font-weight: 600;
    margin: .15rem 0 .6rem; line-height: 1.25;
}
.ped-rule { display: flex; height: 3px; margin-bottom: 1.3rem; }
.ped-rule .g { width: 46px; background: #edc872; }
.ped-rule .t { flex: 1; background: #245d62; }

.section-label {
    font-size: 11px; letter-spacing: .08em; text-transform: uppercase;
    color: #245d62; font-weight: 600;
    padding-bottom: 6px; border-bottom: 1px solid #edc872;
    margin: 16px 0 10px;
}

.pill { font-size: 11px; font-weight: 600; padding: 3px 10px; border-radius: 20px; }
.pill-grant   { color: #854f0b; background: #faeeda; }
.pill-flow    { color: #1a474b; background: #e1efe9; }
.pill-gen     { color: #444441; background: #f1efe8; }
.pill-direct  { color: #72243e; background: #fbeaf0; }
.pill-retired { color: #5f5e5a; background: #e8e8e4; }
.pill-gap     { color: #993c1d; background: #faece7; }
.pill-rev     { color: #1a474b; background: #e1efe9; }
.pill-exp     { color: #444441; background: #f1efe8; }
.pill-hist    { color: #5f5e5a; background: #e8e8e4; }

.badge {
    font-size: 12px; color: #5f5e5a; background: #f1efe8;
    padding: 3px 9px; border-radius: 6px;
}
.badge-mono { font-family: monospace; }

.desc-box {
    background: #f7f6f2; border-left: 3px solid #edc872;
    padding: 10px 14px; border-radius: 0 6px 6px 0;
    font-size: 13px; color: #3a3a38; line-height: 1.55;
    margin-top: 4px;
}
.desc-box.fallback { border-left-color: #cdd7d3; color: #55605c; font-style: italic; }

a { color: #245d62; text-decoration: none; }
a:hover { color: #1a474b; text-decoration: underline; }

.stDownloadButton button {
    width: 100%; background: #245d62; color: #fff !important; border: none;
}
.stDownloadButton button:hover { background: #1a474b; }
.stDownloadButton button p,
.stDownloadButton button span { color: #fff !important; }

[data-testid="stSidebar"] .stMultiSelect [data-baseweb="tag"] {
    background: #245d62 !important;
}
[data-testid="stSidebar"] .stMultiSelect [data-baseweb="tag"] span { color: #fff !important; }
[data-testid="stSidebar"] .stMultiSelect [data-baseweb="tag"] svg  { fill: #fff !important; }

[data-testid="stExpander"] { border: 0.5px solid #ececec; border-radius: 8px; }
</style>
""", unsafe_allow_html=True)

# ─── Logo ─────────────────────────────────────────────────────────────
LOGO_PATH = Path(__file__).parent / "300 DPI NM PED Logo JPEG.jpg"
LOGO_LINK = "https://web.ped.nm.gov/bureaus/school-budget-bureau/"

def _load_logo():
    if not LOGO_PATH.exists() or not HAS_PIL:
        return None
    try:
        buf = BytesIO()
        Image.open(LOGO_PATH).save(buf, format="PNG")
        b64 = base64.b64encode(buf.getvalue()).decode()
        return (
            f'<a href="{LOGO_LINK}" target="_blank">'
            f'<img src="data:image/png;base64,{b64}" '
            f'style="max-height:90px;height:auto;max-width:100%"></a>'
        )
    except Exception:
        return None

logo = _load_logo()
if logo:
    st.sidebar.markdown(logo, unsafe_allow_html=True)
st.sidebar.caption("School Budget Bureau")

# ═════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═════════════════════════════════════════════════════════════════════

# Source of truth: five per-dimension CSVs built by build_ucoa.py.
DATA_DIR = Path(__file__).parent / "data"
DIM_FILES = {
    "Fund":      "ucoa_fund.csv",
    "Function":  "ucoa_function.csv",
    "Object":    "ucoa_object.csv",
    "Program":   "ucoa_program.csv",
    "Job Class": "ucoa_job_class.csv",
}

DIM_CONFIG = {
    "Fund": {
        "title":          "Fund codes",
        "type_col":       "FundType",
        "parent_col":     "ParentFundCode",
        "grant_col":      "IsGrant",
        "grantname_col":  "GrantName",
        "budget_col":     "IsBudgetable",
        "actuals_col":    "ActualsPostable",
        "reimburse_col":  "IsReimbursable",
        "approvals_col":  "RequiresApprovals",
        "assessedval_col":"SupportsAssessedValuations",
        "revobj_col":     "RevObjectCurrYear",
        "revobj_py_col":  "RevObjectPriorYear",
        "chartxfer_col":  "UsesDependentCharterXfer",
        "zeroout_col":    "PEDZeroOut",
        "notinuse_col":   "NotInUse",
        "psab_col":       "PSABDescription",
    },
    "Function":  {"title": "Function codes",  "type_col": "ChartAccountType", "notinuse_col": "NotInUse"},
    "Object":    {"title": "Object codes",    "type_col": "ChartAccountType", "notinuse_col": "NotInUse"},
    "Program":   {"title": "Program codes",   "type_col": "",                 "notinuse_col": "NotInUse"},
    "Job Class": {"title": "Job class codes", "type_col": "JobClassCategory", "notinuse_col": ""},
}

PAGE_SIZE = 10

# ═════════════════════════════════════════════════════════════════════
# HELPERS
# ═════════════════════════════════════════════════════════════════════

def _clean(x) -> str:
    return "" if pd.isna(x) else str(x).strip()

def _is_gap(x) -> bool:
    return _clean(x) in {"????", "?", "TBD", ""}

def _bool_col(val) -> bool:
    return _clean(val).lower() in {"yes", "true", "1", "y"}

def _yn(val) -> str:
    v = _clean(val)
    if v.lower() in {"yes", "true", "1", "y"}:
        return "✓ Yes"
    if v.lower() in {"no", "false", "0", "n"}:
        return "No"
    return v or "—"

def _type_pill(t: str) -> str:
    t = _clean(t)
    tl = t.lower()
    if not t:
        return ""
    if "revenue" in tl:
        return f'<span class="pill pill-rev">{t}</span>'
    if "expenditure" in tl or "expense" in tl:
        return f'<span class="pill pill-exp">{t}</span>'
    if "flow" in tl:
        return f'<span class="pill pill-flow">{t}</span>'
    if "direct" in tl:
        return f'<span class="pill pill-direct">{t}</span>'
    if "general" in tl:
        return f'<span class="pill pill-gen">{t}</span>'
    if "martinez" in tl or "protected" in tl:
        return f'<span class="pill pill-grant">Protected</span>'
    return f'<span class="pill pill-gen">{t}</span>'

def _status_pill(status: str) -> str:
    return '<span class="pill pill-hist">Historical</span>' if _clean(status) == "Historical" else ""

def _fund_category(code: str, parent_cat_name: str = "") -> str:
    """PSAB/GAAP fund category. Prefer ParentCategoryName from the PSAB layer;
    otherwise derive from the code family. This is the *accounting* category —
    distinct from the OBMS 'FundType' system attribute, which classifies funds
    for OBMS processing (e.g. 31100 shows 'General Fund' in OBMS because it
    rolls up under parent fund 30000)."""
    if parent_cat_name:
        return parent_cat_name
    c = _clean(code)
    if not c or not c[0].isdigit():
        return ""
    if c.startswith(("31", "32")):
        return "Capital Projects Funds"
    first = c[0]
    return {
        "1": "General / Operational Funds",
        "2": "Special Revenue Funds",
        "3": "Capital Projects Funds",
        "4": "Debt Service Funds",
        "5": "Permanent Funds",
        "6": "Enterprise / Proprietary Funds",
        "7": "Trust & Agency Funds",
    }.get(first, "")

# ─── BAR routing (BAR/Budget Approvers by Fund, PED sheet upd. 3/28/23) ─
# Loaded from data/bar_approvers.csv; embedded fallback keeps the app
# working if the CSV is missing. Rollup families (24000, 25000, 26000,
# 27000, 28000, 29000, …) apply to their child funds: 24106 → 24000.
_BAR_FALLBACK = {
    "11000": ("Operational", "N/A", "School Budget"),
    "13000": ("Transportation", "Transportation", "Fiscal"),
    "14000": ("Instructional Materials", "Instructional Materials", "Fiscal"),
    "21000": ("Food Service", "Student Success", "Fiscal"),
    "24000": ("Federal Flow-Through", "Multiple", "Fiscal"),
    "25000": ("Federal Direct Grants", "N/A", "School Budget"),
    "26000": ("Local Grants", "N/A", "School Budget"),
    "27000": ("State Flow-Through Grants", "Multiple", "Fiscal"),
    "28000": ("State Direct Grants", "N/A", "School Budget"),
    "29000": ("Combined Local/State Grants", "N/A", "School Budget"),
    "31100": ("Bond Building", "N/A", "School Budget"),
    "41000": ("Debt Service", "N/A", "School Budget"),
}

@st.cache_data(ttl=3600, show_spinner=False)
def _load_bar_approvers() -> dict[str, tuple[str, str, str]]:
    path = DATA_DIR / "bar_approvers.csv"
    try:
        df = pd.read_csv(path, dtype=str, keep_default_na=False)
        return {
            _clean(r["Code"]): (_clean(r["FundDescription"]),
                                _clean(r["PMApproval"]),
                                _clean(r["FinalApproval"]))
            for _, r in df.iterrows() if _clean(r.get("Code", ""))
        }
    except Exception:
        return dict(_BAR_FALLBACK)

def _bar_lookup(code: str) -> tuple[tuple[str, str, str] | None, str]:
    """Exact match first, then rollup fallback (24106 → 24100 → 24000).
    Returns ((desc, pm, final), matched_code) or (None, '')."""
    table = _load_bar_approvers()
    c = _clean(code)
    if not c:
        return None, ""
    candidates = [c]
    if len(c) == 5:
        candidates += [c[:3] + "00", c[:2] + "000"]
    for cand in candidates:
        if cand in table:
            return table[cand], cand
    return None, ""

# Known rollup category heads (not directly budgeted; children carry budgets).
# Per SBB practice: 24/25/26/27/28/29-thousand heads are rollups; the rest of
# the BAR sheet codes are specific funds.
KNOWN_ROLLUPS = {"24000", "25000", "26000", "27000", "28000", "29000"}

def _rollup_codes(df: pd.DataFrame, parent_col: str) -> set[str]:
    """Rollup = a code some other fund points to as its parent, plus the
    known grant-family heads."""
    out = set(KNOWN_ROLLUPS)
    if df.empty or parent_col not in df.columns or "Code" not in df.columns:
        return out
    parents = {_clean(v) for v in df[parent_col] if _clean(v)}
    codes = {_clean(c) for c in df["Code"]}
    return out | (parents & codes)

def _metric_card(label: str, value, alert: bool = False) -> str:
    if alert:
        border = "border:0.5px solid #ecc9c1;border-left:3px solid #c64c43;"
        lab_color, val_color = "#a8584c", "#c64c43"
    else:
        border = "border:0.5px solid #e3e3dd;"
        lab_color, val_color = "#8a8a82", "#245d62"
    return (
        f'<div style="{border}border-radius:8px;padding:13px 15px;">'
        f'<div style="font-size:11px;letter-spacing:.06em;text-transform:uppercase;'
        f'color:{lab_color};">{label}</div>'
        f'<div style="font-size:1.7rem;font-weight:600;color:{val_color};">{value}</div>'
        f'</div>'
    )

# ═════════════════════════════════════════════════════════════════════
# DATA LOADING
# ═════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=3600, show_spinner=False)
def _load_all_dims() -> tuple[dict[str, pd.DataFrame], str, list[str]]:
    data: dict[str, pd.DataFrame] = {}
    errors: list[str] = []
    newest = 0.0
    for dim, fname in DIM_FILES.items():
        path = DATA_DIR / fname
        try:
            df = pd.read_csv(path, dtype=str, keep_default_na=False)
            df.columns = [c.strip() for c in df.columns]
            df = df[df.apply(lambda r: any(_clean(v) for v in r), axis=1)]
            data[dim] = df
            newest = max(newest, path.stat().st_mtime)
        except Exception as e:
            errors.append(f"{dim}: {e}")
            data[dim] = pd.DataFrame()
    ts = datetime.fromtimestamp(newest).strftime("%b %d %Y, %I:%M %p") if newest else "unknown"
    return data, ts, errors

# ═════════════════════════════════════════════════════════════════════
# DETAIL CARDS
# ═════════════════════════════════════════════════════════════════════

def _description_block(row: pd.Series):
    """PSAB description if present; for Fund fall back to the parent-category description."""
    psab = _clean(row.get("PSABDescription", ""))
    if psab:
        st.markdown('<div class="section-label">PSAB description</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="desc-box">{psab}</div>', unsafe_allow_html=True)
        return
    parent_desc = _clean(row.get("ParentCategoryDescription", ""))
    parent_name = _clean(row.get("ParentCategoryName", ""))
    if parent_desc:
        label = f"Parent category — {parent_name}" if parent_name else "Parent category"
        st.markdown(f'<div class="section-label">{label}</div>', unsafe_allow_html=True)
        st.markdown(
            f'<div class="desc-box fallback">No PSAB description for this code. '
            f'Showing the parent category: {parent_desc}</div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            '<div class="desc-box fallback">No PSAB description available for this code.</div>',
            unsafe_allow_html=True,
        )


def display_fund_detail(row: pd.Series, cfg: dict, rollups: set[str] | None = None):
    code       = _clean(row.get("Code", ""))
    name       = _clean(row.get("Name", ""))
    obms_type  = _clean(row.get(cfg.get("type_col", ""), ""))
    parent     = _clean(row.get(cfg.get("parent_col", ""), ""))
    is_grant   = _bool_col(row.get(cfg.get("grant_col", ""), ""))
    grant_name = _clean(row.get(cfg.get("grantname_col", ""), ""))
    status     = _clean(row.get("Status", ""))
    category   = _fund_category(code, _clean(row.get("ParentCategoryName", "")))
    is_rollup  = code in (rollups or set())

    grant_pill  = ' <span class="pill pill-grant">Grant</span>' if is_grant else ""
    gap_pill    = ' <span class="pill pill-gap">⚠ Grant name missing</span>' if (is_grant and _is_gap(grant_name)) else ""
    cat_pill    = f' <span class="pill pill-flow">{category}</span>' if category else ""
    rollup_pill = ' <span class="pill pill-gen">Rollup category</span>' if is_rollup else ""

    st.markdown(
        f'<div style="font-size:1.2rem;font-weight:600;color:#222;">{name}</div>'
        f'<div style="display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin:8px 0 4px;">'
        f'<span class="badge badge-mono">{code}</span>'
        f'{cat_pill}{rollup_pill}{grant_pill}{_status_pill(status)}{gap_pill}'
        f'</div>',
        unsafe_allow_html=True,
    )

    if is_rollup:
        st.markdown(
            '<div style="font-size:12px;color:#55605c;margin:2px 0 6px;">'
            'This is a rollup category, not a directly budgeted fund — '
            'budgets live on its specific child funds.</div>',
            unsafe_allow_html=True,
        )

    _description_block(row)

    st.markdown('<div class="section-label">Fund attributes</div>', unsafe_allow_html=True)
    c1, c2, c3 = st.columns(3)
    with c1:
        st.write(f"**Fund category:** {category or '—'}")
        st.write(f"**OBMS fund type:** {obms_type or '—'}")
        st.write(f"**Parent fund:** {parent or '—'}")
        st.write(f"**Is grant:** {_yn(row.get(cfg.get('grant_col',''),''))}")
        st.write(f"**Grant name:** {grant_name if not _is_gap(grant_name) else '⚠ Missing'}")
    with c2:
        st.write(f"**Budgetable:** {_yn(row.get(cfg.get('budget_col',''),''))}")
        st.write(f"**Actuals postable:** {_yn(row.get(cfg.get('actuals_col',''),''))}")
        st.write(f"**Reimbursable:** {_yn(row.get(cfg.get('reimburse_col',''),''))}")
        st.write(f"**Requires approvals:** {_yn(row.get(cfg.get('approvals_col',''),''))}")
    with c3:
        st.write(f"**Supports assessed valuations:** {_yn(row.get(cfg.get('assessedval_col',''),''))}")
        st.write(f"**Uses dependent charter xfer:** {_yn(row.get(cfg.get('chartxfer_col',''),''))}")
        st.write(f"**PED zero-out:** {_yn(row.get(cfg.get('zeroout_col',''),''))}")
        st.write(f"**Status:** {status or '—'}")
    st.caption(
        "Fund category is the PSAB/GAAP classification. OBMS fund type is a "
        "system attribute from the COA Configuration Report and may differ "
        "(e.g. capital funds under parent 30000 show as “General Fund” in OBMS)."
    )

    # ── BAR routing ───────────────────────────────────────────────────
    bar, matched = _bar_lookup(code)
    st.markdown('<div class="section-label">BAR routing</div>', unsafe_allow_html=True)
    if bar:
        desc, pm, final = bar
        inherited = matched != code
        via = (
            f' <span style="font-size:12px;color:#8a8a82;">— inherited from '
            f'rollup <span style="font-family:monospace;">{matched}</span> ({desc})</span>'
            if inherited else ""
        )
        st.markdown(
            f'<div style="font-size:14px;color:#3a3a38;line-height:1.7;">'
            f'<b>PM approval:</b> {pm} &nbsp;·&nbsp; '
            f'<b>Final approval:</b> {final}{via}</div>'
            f'<div style="font-size:12px;color:#8a8a82;margin-top:4px;">'
            f'Source: BAR/Budget Approvers by Fund (upd. 3/28/23). For PM contacts, '
            f'run OBMS → Reports → Personnel Reports → <i>Users in Roles by Fund</i>.</div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            '<div style="font-size:13px;color:#8a8a82;">No BAR routing entry '
            'found for this fund or its rollup family.</div>',
            unsafe_allow_html=True,
        )

    # Allowable object/function/program combinations live in OBMS, not in this field.
    st.markdown(
        '<div class="section-label">Allowable combinations</div>'
        f'<div style="font-size:13px;color:#55605c;line-height:1.55;">'
        f'Valid combinations for this fund are defined in OBMS. '
        f'<a href="https://obms.ped.state.nm.us/PED_OBMS/Reports" target="_blank">'
        f'Open the Chart Line Listing Report&nbsp;→</a> — select the current Chart of '
        f'Accounts, then set Start&nbsp;Fund and End&nbsp;Fund to {code}.</div>',
        unsafe_allow_html=True,
    )


def display_generic_detail(row: pd.Series, dim: str, cfg: dict):
    code     = _clean(row.get("Code", ""))
    name     = _clean(row.get("Name", ""))
    type_col = cfg.get("type_col", "")
    type_val = _clean(row.get(type_col, "")) if type_col else ""
    status   = _clean(row.get("Status", ""))

    st.markdown(
        f'<div style="font-size:1.2rem;font-weight:600;color:#222;">{name}</div>'
        f'<div style="display:flex;gap:8px;align-items:center;margin:8px 0;">'
        f'<span class="badge badge-mono">{code}</span>'
        f'{_type_pill(type_val)}{_status_pill(status)}'
        f'</div>',
        unsafe_allow_html=True,
    )

    _description_block(row)

    st.markdown('<div class="section-label">Attributes</div>', unsafe_allow_html=True)
    hide = {"Code", "Name", "PSABDescription", "ParentCategoryDescription",
            "ParentCategoryName", "Status"}
    fields = [(col, _clean(row[col])) for col in row.index if col not in hide and _clean(row[col])]
    if not fields:
        st.write("No additional detail available.")
        return
    c1, c2 = st.columns(2)
    half = len(fields) // 2 + len(fields) % 2
    for i, (k, v) in enumerate(fields):
        (c1 if i < half else c2).write(f"**{k}:** {v}")


# ═════════════════════════════════════════════════════════════════════
# MAIN APP
# ═════════════════════════════════════════════════════════════════════

st.markdown(
    '<div class="ped-eyebrow">New Mexico PED · School Budget Bureau</div>'
    '<div class="ped-title">UCOA Reference Explorer</div>'
    '<div class="ped-rule"><span class="g"></span><span class="t"></span></div>',
    unsafe_allow_html=True,
)

# ── Sidebar: data ─────────────────────────────────────────────────────
st.sidebar.header("Data")
if st.sidebar.button("Refresh data"):
    st.cache_data.clear()
    st.rerun()

all_data, built_ts, load_errors = _load_all_dims()

if load_errors and all(df.empty for df in all_data.values()):
    st.error(
        "No source-of-truth data found in ./data. "
        "Run `python build_ucoa.py COA_Configuration_Report.csv` to generate it, "
        "then use **Refresh data**."
    )
    for err in load_errors:
        st.caption(err)
    st.stop()

st.sidebar.success(f"Source of truth built {built_ts}")
for err in load_errors:
    st.sidebar.warning(err)

# ── Dimension selector ────────────────────────────────────────────────
st.sidebar.markdown("### Dimension")
dim_options = list(DIM_FILES.keys())
dim_counts  = {d: len(all_data.get(d, [])) for d in dim_options}
dim_labels  = [f"{d}  ({dim_counts[d]})" for d in dim_options]
dim_idx = st.sidebar.radio(
    "Select dimension",
    range(len(dim_options)),
    format_func=lambda i: dim_labels[i],
    label_visibility="collapsed",
)
active_dim = dim_options[dim_idx]
df_active  = all_data.get(active_dim, pd.DataFrame())
cfg        = DIM_CONFIG.get(active_dim, {})
type_col   = cfg.get("type_col", "")

# ── Filters ───────────────────────────────────────────────────────────
st.sidebar.markdown("### Filters")

sel_types = []
if type_col and type_col in df_active.columns:
    all_types = sorted(t for t in df_active[type_col].dropna().unique().tolist() if _clean(t))
    if all_types:
        sel_types = st.sidebar.multiselect("Type", all_types, default=all_types)

# Universal status filter (every dimension carries Status now)
show_active_only = False
if "Status" in df_active.columns:
    show_active_only = st.sidebar.checkbox("Active only (exclude Historical)")

# PSAB coverage filter
show_described_only = False
show_undescribed_only = False
if "PSABDescription" in df_active.columns:
    show_described_only   = st.sidebar.checkbox("Has PSAB description")
    show_undescribed_only = st.sidebar.checkbox("Missing PSAB description")

# Fund-specific
show_grants_only = show_gaps_only = show_budgetable_only = False
if active_dim == "Fund":
    show_grants_only     = st.sidebar.checkbox("Grants only")
    show_gaps_only       = st.sidebar.checkbox("Missing grant names (????)")
    show_budgetable_only = st.sidebar.checkbox("Budgetable only")

if st.sidebar.button("Reset filters"):
    st.rerun()

# ── Search ────────────────────────────────────────────────────────────
s1, s2 = st.columns([3, 1])
with s1:
    search = st.text_input("Search", placeholder="Code, name, description, grant name…")
with s2:
    st.markdown("<div style='height:1.75rem'></div>", unsafe_allow_html=True)
    search_all = st.checkbox("All dimensions", value=True,
                             help="Search every UCOA dimension at once, regardless of the selected tab.")

FUND_ROLLUPS = _rollup_codes(all_data.get("Fund", pd.DataFrame()),
                             DIM_CONFIG["Fund"].get("parent_col", ""))

def _search_mask(df: pd.DataFrame, q: str) -> pd.Series:
    mask = pd.Series(False, index=df.index)
    for c in df.select_dtypes(include="object").columns:
        mask |= df[c].astype(str).str.lower().str.contains(q, na=False)
    return mask

# ═════════════════════════════════════════════════════════════════════
# GLOBAL SEARCH MODE — query spans every dimension
# ═════════════════════════════════════════════════════════════════════

if search and search_all:
    q = search.lower()
    st.caption("Searching all dimensions — sidebar filters apply to browse mode only.")
    grand_total = 0
    GLOBAL_CAP = 10  # expanders shown per dimension

    for dim in DIM_FILES:
        df = all_data.get(dim, pd.DataFrame())
        if df.empty:
            continue
        hits = df[_search_mask(df, q)]
        if hits.empty:
            continue
        grand_total += len(hits)
        dcfg = DIM_CONFIG.get(dim, {})
        st.markdown(f"#### {dim} ({len(hits)})")
        for _, row in hits.head(GLOBAL_CAP).iterrows():
            code   = _clean(row.get("Code", ""))
            name   = _clean(row.get("Name", ""))
            status = _clean(row.get("Status", ""))
            tags = []
            if dim == "Fund":
                cat = _fund_category(code, _clean(row.get("ParentCategoryName", "")))
                if cat:
                    tags.append(cat)
                if code in FUND_ROLLUPS:
                    tags.append("rollup")
            elif dcfg.get("type_col") and _clean(row.get(dcfg["type_col"], "")):
                tags.append(_clean(row.get(dcfg["type_col"], "")))
            if status == "Historical":
                tags.append("historical")
            suffix = (" · " + " · ".join(tags)) if tags else ""
            with st.expander(f"**{code}** — {name}{suffix}", expanded=(len(hits) == 1 and grand_total == 1)):
                if dim == "Fund":
                    display_fund_detail(row, dcfg, FUND_ROLLUPS)
                else:
                    display_generic_detail(row, dim, dcfg)
        if len(hits) > GLOBAL_CAP:
            st.caption(f"Showing first {GLOBAL_CAP} of {len(hits)} — refine your search to narrow results.")

    if grand_total == 0:
        st.info("No codes match your search in any dimension.")
    st.stop()

# ── Apply filters ─────────────────────────────────────────────────────
view = df_active.copy()

if sel_types and type_col in view.columns:
    view = view[view[type_col].isin(sel_types)]

if show_active_only and "Status" in view.columns:
    view = view[view["Status"] != "Historical"]

if show_described_only and "PSABDescription" in view.columns:
    view = view[view["PSABDescription"].str.len() > 0]

if show_undescribed_only and "PSABDescription" in view.columns:
    view = view[view["PSABDescription"].str.len() == 0]

if active_dim == "Fund":
    if show_grants_only and cfg["grant_col"] in view.columns:
        view = view[view[cfg["grant_col"]].str.lower().isin({"yes", "true", "1", "y"})]
    if show_gaps_only and cfg["grantname_col"] in view.columns:
        view = view[view[cfg["grantname_col"]].apply(_is_gap)]
    if show_budgetable_only and cfg["budget_col"] in view.columns:
        view = view[view[cfg["budget_col"]].str.lower().isin({"yes", "true", "1", "y"})]

if search:
    view = view[_search_mask(view, search.lower())]

# ── Metrics ───────────────────────────────────────────────────────────
total_in_dim = len(df_active)
showing      = len(view)
described_n  = int((df_active["PSABDescription"].str.len() > 0).sum()) if "PSABDescription" in df_active.columns else 0
historical_n = int((df_active["Status"] == "Historical").sum()) if "Status" in df_active.columns else 0

m1, m2, m3, m4 = st.columns(4)
m1.markdown(_metric_card("Total codes", total_in_dim), unsafe_allow_html=True)
m2.markdown(_metric_card("Showing", showing), unsafe_allow_html=True)

if active_dim == "Fund":
    gc = cfg.get("grant_col", "")
    grants_n = int(df_active[gc].str.lower().isin({"yes", "true", "1", "y"}).sum()) if gc in df_active.columns else 0
    m3.markdown(_metric_card("Grant funds", grants_n), unsafe_allow_html=True)
    m4.markdown(_metric_card("Historical", historical_n), unsafe_allow_html=True)
else:
    m3.markdown(_metric_card("PSAB described", described_n), unsafe_allow_html=True)
    m4.markdown(_metric_card("Historical", historical_n), unsafe_allow_html=True)

st.markdown("<div style='height:1rem'></div>", unsafe_allow_html=True)

# ═════════════════════════════════════════════════════════════════════
# PAGINATED CODE BROWSER
# ═════════════════════════════════════════════════════════════════════

dim_page_key = f"page_{active_dim}"
if dim_page_key not in st.session_state:
    st.session_state[dim_page_key] = 0

if len(view) == 0:
    st.info("No codes match your filters.")
else:
    total_pages = max(1, -(-len(view) // PAGE_SIZE))
    page  = min(st.session_state[dim_page_key], total_pages - 1)
    start = page * PAGE_SIZE
    end   = min(start + PAGE_SIZE, len(view))
    page_df = view.iloc[start:end]

    dim_title = cfg.get("title", f"{active_dim} codes")
    st.markdown(f"#### {dim_title.capitalize()} ({start+1}–{end} of {showing})")

    for _, row in page_df.iterrows():
        code     = _clean(row.get("Code", ""))
        name     = _clean(row.get("Name", ""))
        type_val = _clean(row.get(type_col, "")) if type_col else ""
        status   = _clean(row.get("Status", ""))
        has_desc = len(_clean(row.get("PSABDescription", ""))) > 0

        is_grant   = _bool_col(row.get(cfg.get("grant_col", ""), "")) if active_dim == "Fund" else False
        grant_name = _clean(row.get(cfg.get("grantname_col", ""), "")) if active_dim == "Fund" else ""

        tags = []
        if active_dim == "Fund":
            cat = _fund_category(code, _clean(row.get("ParentCategoryName", "")))
            if cat:
                tags.append(cat)
            if code in FUND_ROLLUPS:
                tags.append("rollup")
        elif type_val:
            tags.append(type_val)
        if is_grant:
            tags.append("Grant")
        if is_grant and _is_gap(grant_name):
            tags.append("⚠ no grant name")
        if status == "Historical":
            tags.append("historical")
        if not has_desc:
            tags.append("no PSAB desc")
        suffix = (" · " + " · ".join(tags)) if tags else ""
        label = f"**{code}** — {name}{suffix}"

        with st.expander(label, expanded=False):
            if active_dim == "Fund":
                display_fund_detail(row, cfg, FUND_ROLLUPS)
            else:
                display_generic_detail(row, active_dim, cfg)

    pcol1, pcol2, pcol3, pcol4, pcol5 = st.columns([1, 1, 2, 1, 1])
    with pcol1:
        if st.button("First", disabled=(page == 0), key=f"pg_first_{active_dim}"):
            st.session_state[dim_page_key] = 0; st.rerun()
    with pcol2:
        if st.button("‹ Prev", disabled=(page == 0), key=f"pg_prev_{active_dim}"):
            st.session_state[dim_page_key] = page - 1; st.rerun()
    with pcol3:
        st.markdown(
            f"<div style='text-align:center;padding-top:6px;color:#8a8a82'>"
            f"Page {page+1} of {total_pages}</div>",
            unsafe_allow_html=True,
        )
    with pcol4:
        if st.button("Next ›", disabled=(page >= total_pages - 1), key=f"pg_next_{active_dim}"):
            st.session_state[dim_page_key] = page + 1; st.rerun()
    with pcol5:
        if st.button("Last", disabled=(page >= total_pages - 1), key=f"pg_last_{active_dim}"):
            st.session_state[dim_page_key] = total_pages - 1; st.rerun()

# ═════════════════════════════════════════════════════════════════════
# DATA TABLE & DOWNLOADS
# ═════════════════════════════════════════════════════════════════════

with st.expander("Data table", expanded=False):
    st.dataframe(view, width="stretch", height=400)

st.subheader("Downloads")
dl1, dl2 = st.columns(2)
with dl1:
    st.download_button(
        f"Filtered ({active_dim})",
        view.to_csv(index=False).encode("utf-8-sig"),
        f"ucoa_{active_dim.lower().replace(' ', '_')}_filtered.csv",
        "text/csv",
    )
with dl2:
    combined = pd.concat(
        [df.assign(Dimension=dim) for dim, df in all_data.items() if not df.empty],
        ignore_index=True,
    )
    st.download_button(
        "All dimensions (combined CSV)",
        combined.to_csv(index=False).encode("utf-8-sig"),
        "ucoa_all_dimensions.csv",
        "text/csv",
    )

st.markdown("---")
st.caption("New Mexico Public Education Department · School Budget Bureau · reads ./data built by build_ucoa.py")